# Generated by Django 4.1.dev20211105111118 on 2021-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_blogpost_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='telegram_media_group_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
