# Generated by Django 4.1.dev20211105111118 on 2021-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0004_blogpost_telegram_media_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='telegram_media_group_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
